### ISSUE TITLE
status indicators for output cells

### ISSUE THREAD

**Issue by willwhitney** [jupyter/jupyter-js-output-area#6]
One way to use this which I imagine will be very standard is with a separate output area for each input cell. In that situation, it is very helpful to have a "working" spinner and a success indicator to show the user what's going on.

**Comment by jdfreder** [comment]
I like this idea- although, admittedly, I'm not sure it needs to live this low in the code.  What prevents you from just using a status indicator div instead of the output area div, at a higher level?

**Comment by willwhitney** [comment]
Yup, sure. Just pointing out that almost everyone is going to have to do
this.

**Comment by jdfreder** [comment]
In the notebook we have now, there are two indicators.  One for the entire page and one for the cell as a whole.  The second one of the two is the most similar to what you suggest, but right now that is done using the cell prompt, which isn't part of the output area and is instead part of the input area.  I could see it being a part of either or both, since the input is the piece that makes the execute request, where the output waits for the response.  Are you suggesting moving the indicator it to the output area?  Or adding another indicator, instead to the output area?

**Comment by willwhitney** [comment]
These are good questions. Personally I think having an indicator in the output area makes sense. However, we shouldn’t make decisions about the notebook UI here, so you're right that this shouldn't live in here.

**Comment by jdfreder** [comment]
Yeah, I was thinking of this component as a thin layer on top of transformime. .... like a Transformime array thingy, but not much more.  Along that same tone, I don't think the "collapsing" output feature should live in this repo - it's very notebook specific.

**Comment by willwhitney** [comment]
Agreed!
