### ISSUE TITLE
Apply styling

### ISSUE THREAD

**Issue by jdfreder** [jupyter/jupyter-js-output-area#8]
@ellisonbg mentioned that there is a lot of styling that the notebook makes on output areas.  We should think about and add styling as appropriate.  The solution should be configurable, so that someone could use their own styling if desired.

**Comment by ellisonbg** [comment]
+1, when we do this we should also decide on a namespace convention for our css classes. Some options:
- `j-oa-class`
- `jpy-oa-class`
- `jupyter-oa-class`
- `jupyter-outputarea-class`

???

**Comment by ellisonbg** [comment]
Here are some of the style files the output area uses:

https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/outputarea.less

https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/ansicolors.less

https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/renderedhtml.less

May be a few others though...

**Comment by jdfreder** [comment]
lol, why all of the `-class`es?  How about
- `jupyter-oa`
- `jupyter-outputarea`

**Comment by ellisonbg** [comment]
Ahh, because, it is likely that there will be a number of CSS classes used
within the output area code for different purposes. The `-class` is just a
placeholder for those names.

On Thu, Aug 13, 2015 at 3:39 PM, Jonathan Frederic <notifications@github.com

> wrote:
> 
> lol, why all of the -classes?
> - jupyter-oa
> - jupyter-outputarea
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-output-area/issues/8#issuecomment-130868834
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Oh, I was under the impression we'd use one unique class name at the top, and normal names further down.  Then nesting could be used to target the different things.

```
`.jupyter-outputarea`
\___ `.output`
        \___ `.text-html`
        \___ `.text-md`
                \___ `h1`
```

**Comment by ellisonbg** [comment]
Ahh, yes. But I thought that approach only solved some classes of CSS
conflicts, but I am not remembering the details. Do you remember?

On Thu, Aug 13, 2015 at 4:53 PM, Jonathan Frederic <notifications@github.com

> wrote:
> 
> Oh, I was under the impression we'd use one unique class name at the top,
> and normal names further down. Then nesting could be used to target the
> different things.
> 
> `.jupyter-outputarea`
> ___ `.output`
>         ___ `.text-html`
>         ___ `.text-md`
>                 ___ `h1`
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-output-area/issues/8#issuecomment-130889946
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
The class hierarchy from jdfreder looks great to me. I don't think we should apply any styling. If we need a prefix, it should be Jupyter. Then we should document their existence.

I'm against styling in a nested component as it forces people to have to override rather than target selectors, variables, and nested contexts. This flies in the face of modularity and makes it difficult for designers and developers to reason about.

Providing a default style sheet that maps to the current notebook makes sense.

**Comment by ellisonbg** [comment]
I think there are some subtle issues about CSS to work through here...

i can imagine there are two types of CSS for components:
1. Low level styling that is required to have a component look any way
   decent at all. I think this should be bundled with components, otherwise
   people will complain about them looking bad.
2. Theme level styling that control. I think it should absolutely possible
   to theme components or sets of components from the outside. I think it is
   reasonable that this wouldn't be shipped with the components.

The main question I have is where to draw the line between these two
categories. Originally, I was thinking that a "default" theme should ship
with the components. The logic there is that it breaks modularity to not
ship a components default style with the components (think about the idea
of web components).

But I should clarify my goals here - I don't really care about how we
accomplish it - I simply think that our components should _never_ look bad
and should always have an great default design and easy to manage themes
and customization of styling. If that means no CSS in the base components
and separate theme packages, I am fine with that.

I should also mention my bias towards us being mildly biased about design,
as the current notebook is. Our designs are really lightweight - but we do
make a lot of choices in our default design (not saying we don't have room
for improvement).

On Sun, Aug 16, 2015 at 5:29 AM, Kyle Kelley notifications@github.com
wrote:

> The class hierarchy from jdfreder looks great to me. I don't think we
> should apply any styling. If we need a prefix, it should be Jupyter. Then
> we should document their existence.
> 
> I'm against styling in a nested component as it forces people to have to
> override rather than target selectors, variables, and nested contexts. This
> flies in the face of modularity and makes it difficult for designers and
> developers to reason about.
> 
> Providing a default style sheet that maps to the current notebook makes
> sense.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-output-area/issues/8#issuecomment-131539924
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
I read over both of your comments and I'm not sure where you agree or disagree, and I mostly agree with both of your points.  I think @rgbkrk 's idea to distribute a stylesheet with the output area, but not apply it to the element itself, is cleanest way forward.  That way the API use has both an HTMLElement and a style sheet, they can then do what they want with one or both.

I also agree with @ellisonbg 's idea that there are two levels of detail here.  The first, and most essential, being that we provide some styling in our sheet to make things render correctly in the largest number of environments that we can.  Think images, sizing, alignment, etc..

I think the second level of detail, theme type styling, should exist at a higher level in the notebook app itself.  Theme level styling really only applies to the notebook.

**Comment by rgbkrk** [comment]
I'd suggest this layout, for the sake of namespaces and scoping:

```
`.jupyter-output-area`
\___ `.jupyter-output`
        \___ `.text-html`
        \___ `.text-md`
                \___ `h1`
```

**Comment by rgbkrk** [comment]
Closing, since this repo is now deprecated.
